[project]
name = "plateau"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[dependencies]
python = ">=3.11"
dask = ">=2022.5.1"
decorator = "*"
msgpack-python = ">=0.5.2"
numpy = "!=1.15.0,!=1.16.0,<2"
pandas = ">=0.23.0,!=1.0.0"
pyarrow = ">=4"
simplejson = "*"
minimalkv = ">=1.4.2"
toolz = "*"
urlquote = ">=1.1.3"
zstandard = "*"
attrs = "*"
click = "*"
prompt-toolkit = "*"
pyyaml = "*"


[host-dependencies]
pip = "*"
setuptools = ">=61"
setuptools-scm = "*"

[feature.test.dependencies]
pytest = ">=6"
pytest-cov = "*"
pytest-mock = "*"
freezegun = "*"
mypy = "*"
distributed = ">=2022.5.1"
pytz = "*"
cloudpickle = "*"
hypothesis = "*"
[feature.test.tasks]
test = "pytest"
test-coverage = "pytest --cov=plateau --cov-report=xml --cov-report=term-missing"

[feature.build.dependencies]
python-build = "*"
twine = "*"
[feature.build.tasks]
build-wheel = "python -m build --no-isolation ."
check-wheel = "twine check dist/*"

[feature.lint.dependencies]
pre-commit = "*"
insert-license-header = "*"
docformatter = "*"
ruff = "*"
prettier = "*"
taplo = "*"
pre-commit-hooks = "*"
typos = "*"
[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[feature.benchmark.dependencies]
asv = "*"
libmambapy = "*"
conda = "*"

[feature.docs.dependencies]
sphinx = "*"
jinja2 = "<3.1"
sphinx_rtd_theme = "*"
IPython = "*"
[feature.docs.tasks]
# Run task `postinstall` before building docs in docs environment
docs = "cd docs && make html"
readthedocs = "rm -rf $READTHEDOCS_OUTPUT/html && cp -r docs/_build/html $READTHEDOCS_OUTPUT/html"


[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[environments]
default = ["test"]
py311 = ["py311", "test"]
py312 = ["py312", "test"]
build = ["build"]
benchmark = ["benchmark", "test"]
docs = ["docs", "test"]
lint = { features = ["lint"], no-default-feature = true }
