name: Benchmarks

on:
  schedule:
    - cron: "0 0 * * 0" # weekly on Sunday

jobs:
  benchmarks:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@dbaed5efa0bd33d6bd6d162bec8a06d8fc43c807 # v0.8.5
        with:
          environments: benchmark
      - name: Install package
        run: pixi run -e benchmark postinstall
      - name: Running benchmarks
        run: |
          pixi run -e benchmark asv --config ./asv_bench/asv.conf.json machine --machine github --os unknown --arch unknown --cpu unknown --ram unknown
          pixi run -e benchmark asv --config ./asv_bench/asv.conf.json run -E existing:same | sed "/failed$/ s/^/##[error]/" | tee benchmarks.log
          if grep "failed" benchmarks.log > /dev/null ; then
              exit 1
          fi
