name: Benchmarks

on:
  schedule:
    - cron: "0 0 * * 0" # weekly on Sunday

jobs:
  benchmarks:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@194d461b21b6c5717c722ffc597fa91ed2ff29fa # v0.9.1
        with:
          environments: benchmark
      - name: Install package
        run: pixi run -e benchmark postinstall
      - name: Running benchmarks
        run: |
          pixi run -e benchmark asv --config ./asv_bench/asv.conf.json machine --machine github --os unknown --arch unknown --cpu unknown --ram unknown
          pixi run -e benchmark asv --config ./asv_bench/asv.conf.json run -E existing:same | sed "/failed$/ s/^/##[error]/" | tee benchmarks.log
          if grep "failed" benchmarks.log > /dev/null ; then
              exit 1
          fi
