name: Benchmarks

on:
  schedule:
    - cron: "0 0 * * 0" # weekly on Sunday

jobs:
  benchmarks:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@307e5e5842748e3752d5178fbd158e0a6c1b55ff # v0.8.12
        with:
          environments: benchmark
      - name: Install package
        run: pixi run -e benchmark postinstall
      - name: Running benchmarks
        run: |
          pixi run -e benchmark asv --config ./asv_bench/asv.conf.json machine --machine github --os unknown --arch unknown --cpu unknown --ram unknown
          pixi run -e benchmark asv --config ./asv_bench/asv.conf.json run -E existing:same | sed "/failed$/ s/^/##[error]/" | tee benchmarks.log
          if grep "failed" benchmarks.log > /dev/null ; then
              exit 1
          fi
