name: CI

on:
  pull_request:
  push:
    branches:
      - "main"
      - "pre-commit-autoupdate"
      - "update-pixi"
    tags:
      - "*"
  schedule:
    # daily (`@daily` not supported, see
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events )
    #
    # Runs on default/base branch (see
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule )
    - cron: "0 0 * * *"

jobs:
  pre-commit:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659 # v0.8.1
        with:
          environments: default lint
      - name: pre-commit
        run: pixi run pre-commit-run --color=always --show-diff-on-failure

  tests:
    strategy:
      fail-fast: false
      matrix:
        environment:
          [
            "py310-pyarrow15-0-2",
            "py310-pyarrow16-1",
            "py310-pyarrow17-0",
            "py310-pyarrow18-1",
            "py311-pyarrow15-0-2",
            "py311-pyarrow16-1",
            "py311-pyarrow17-0",
            "py311-pyarrow18-1",
            "py312-pyarrow15-0-2",
            "py312-pyarrow16-1",
            "py312-pyarrow17-0",
            "py312-pyarrow18-1",
          ]

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659 # v0.8.1
        with:
          environments: ${{ matrix.environment }} # References the environments defined in pixi.toml
      - name: Install repository
        run: pixi run postinstall

      - name: Pytest
        run: pixi run test-coverage -n auto

      - name: Codecov
        uses: codecov/codecov-action@v5.1.2
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          name: pytest-${{ matrix.environment }}
