name: Nightlies
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  nightlies:
    name: Nightlies
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [
            # nightlies (e.g. pyarrow) will be installed in the following steps
            "py310-pyarrow18-1",
            "py311-pyarrow18-1",
            "py312-pyarrow18-1",
            "py313-pyarrow18-1",
          ]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@307e5e5842748e3752d5178fbd158e0a6c1b55ff # v0.8.12
        with:
          environments: ${{ matrix.environment }}

      - name: Install Pyarrow nightly
        # The nightlies channel for conda is currently empty: https://github.com/apache/arrow/issues/41856
        # We therefore rely on the pip nightlies: https://github.com/data-engineering-collective/plateau/pull/184#discussion_r1888429974
        run: pixi run pip install --extra-index-url https://pypi.fury.io/arrow-nightlies/ --prefer-binary --pre pyarrow
      - name: Pip Install NumFOCUS nightly
        # NumFOCUS nightly wheels, contains numpy and pandas
        # TODO(gh-45): Re-add numpy
        run: pixi run python -m pip install --pre --upgrade --timeout=60 --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/ pandas

      - name: Install repository
        run: pixi run postinstall

      - name: Pytest
        run: pixi run test-coverage -n auto
